// @vitest-environment jsdom
import { act, cleanup, fireEvent, render, screen } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import App from '../App.jsx'
import { effectiveDusk } from '../engine/index.js'
vi.mock('../engine/index.js', async original => ({ ...await original(), effectiveDusk: vi.fn() }))
const profile = { name: 'Fictional Sam', birthYear:1942, lat:32.7, lon:-96.8, city:'Dallas', anchors:{} }
const read = () => JSON.parse(localStorage.getItem('moonrise:v1'))
const click = name => fireEvent.click(screen.getByRole('button', { name, exact:true }))
beforeEach(() => {
  vi.useFakeTimers(); vi.setSystemTime(new Date('2026-09-26T23:00:00Z'))
  localStorage.clear(); localStorage.setItem('moonrise:v1', JSON.stringify({ profile, logs:[] }))
  vi.spyOn(HTMLMediaElement.prototype, 'pause').mockImplementation(() => {})
  vi.spyOn(HTMLMediaElement.prototype, 'load').mockImplementation(() => {})
  effectiveDusk.mockResolvedValue({ sunset:new Date('2026-09-27T00:00:00Z'), effectiveDusk:new Date('2026-09-27T00:00:00Z'), cloudCover:0, source:'offline' })
})
afterEach(() => { cleanup(); vi.useRealTimers(); vi.restoreAllMocks() })
it('keeps declined and quiet events when rapid updates occur, with a source-linked handoff', async () => {
  await act(async () => render(<App/>))
  click('Try a fictional session'); click('Skip launch')
  click('They declined this activity')
  click('Record that we started')
  fireEvent.change(screen.getByLabelText(/What did you notice/), { target:{ value:'Sat together by the window.' } })
  click('Add observation'); click('Finish')
  const saved = read()
  expect(saved.logs).toEqual([])
  expect(saved.tonight).toBeUndefined()
  expect(saved.sessions).toHaveLength(1)
  expect(saved.sessions[0].isDemo).toBe(true)
  expect(saved.sessions[0].events.map(e => e.type)).toEqual(['offered','declined','offered','started','observation','stopped','finished'])
  expect(saved.sessions[0].events.find(e => e.type === 'observation').text).toBe('Sat together by the window.')
})
it('saves a prepared plan and snapshots it into a new session without changing old logs', async () => {
  const log = {date:'2026-09-25', outcome:'calm', songIds:[]}
  localStorage.setItem('moonrise:v1', JSON.stringify({profile,logs:[log]}))
  await act(async () => render(<App/>))
  click('Prepare their evening')
  fireEvent.change(screen.getByLabelText('A familiar place or interest'), {target:{value:'The garden'}})
  fireEvent.change(screen.getByLabelText('A short story to share'), {target:{value:'We planted tomatoes.'}})
  click('Save evening plan'); click('Start Moonrise now'); click('Skip launch')
  const saved = read()
  expect(saved.sessions[0].plan.story).toBe('We planted tomatoes.')
  expect(saved.sessions[0].isDemo).toBe(false)
  expect(saved.logs[0]).toMatchObject(log)
})
it('keeps actual personal prompts out of fictional sessions', async () => {
  localStorage.setItem('moonrise:v1',JSON.stringify({profile,logs:[],approvedPrompts:['Private family anchor never used in examples.']}))
  await act(async () => render(<App/>))
  click('Try a fictional session'); click('Skip launch'); click('A little music')
  expect(screen.queryByText('Private family anchor never used in examples.')).toBeNull()
  fireEvent.playing(document.querySelector('audio'))
  click('Stop music')
  fireEvent.playing(document.querySelector('audio'))
  expect(read().sessions[0].events.filter(e=>e.type==='started' && e.source==='player')).toHaveLength(2)
  expect(read().tonight).toBeUndefined()
})
it('retains an unsubmitted observation when Finish is pressed', async () => {
  await act(async () => render(<App/>))
  click('Try a fictional session'); click('Skip launch')
  fireEvent.change(screen.getByLabelText(/What did you notice/),{target:{value:'Unsubmitted draft'}})
  click('Finish')
  expect(screen.getByLabelText(/What did you notice/).value).toBe('Unsubmitted draft')
  expect(read().sessions[0].events.some(e=>e.type==='finished')).toBe(false)
  click('Clear draft'); click('Finish')
  expect(read().sessions[0].events.some(e=>e.type==='finished')).toBe(true)
  expect(read().sessions[0].events.some(e=>e.type==='observation')).toBe(false)
})
it('keeps a quiet-only plan quiet and does not offer excluded stories', async () => {
  localStorage.setItem('moonrise:v1', JSON.stringify({ profile, logs:[], eveningPlan:{ activities:['quiet'] } }))
  await act(async () => render(<App/>))
  click('Start Moonrise now'); click('Skip launch')
  expect(screen.getByRole('button',{name:'Quiet view',exact:true}).disabled).toBe(true)
  expect(screen.queryByRole('button',{name:'Show conversation',exact:true})).toBeNull()
  expect(screen.queryByRole('button',{name:'A familiar story',exact:true})).toBeNull()
})
it.each(['pause','ended'])('records the player %s once and does not invent a later stop on Finish', async event => {
  await act(async () => render(<App/>))
  click('Try a fictional session'); click('Skip launch'); click('A little music')
  const audio = document.querySelector('audio')
  fireEvent.playing(audio); fireEvent[event](audio)
  expect(read().sessions[0].events.filter(e => e.type === 'stopped')).toHaveLength(1)
  click('Finish')
  const stops = read().sessions[0].events.filter(e => e.type === 'stopped')
  expect(stops).toHaveLength(1)
  expect(stops[0].source).toBe('player')
})

it('previews the selected activity and opens it after the single launch', async () => {
  await act(async () => render(<App/>))
  click('A little music')
  expect(screen.getByRole('status').textContent).toBe('Open the listening library and play a recording in the app.')
  expect(screen.queryByRole('button', {name:/moonflight/i})).toBeNull()
  click('Start Moonrise now')
  expect(screen.getByRole('dialog')).toBeTruthy()
  await act(async () => vi.advanceTimersByTime(2400))
  expect(screen.getByRole('region', {name:'Shared activity'}).textContent).toContain('Music')
  expect(document.querySelector('audio').autoplay).toBe(false)
  click('Finish')
  expect(screen.getByRole('heading', {name:'How was tonight?'})).toBeTruthy()
  click('Restless')
  expect(read().logs[0].outcome).toBe('restless')
  expect(read().sessions[0].events.at(-1).text).toBe('Evening indicator: restless.')
  expect(screen.getByRole('heading', {name:'Session handoff'})).toBeTruthy()
})
it('records fictional indicators without overwriting the real evening', async () => {
  const real = {date:'2026-09-26',outcome:'restless',songIds:[]}
  localStorage.setItem('moonrise:v1', JSON.stringify({profile,logs:[real]}))
  await act(async () => render(<App/>))
  click('Try a fictional session'); click('Skip launch'); click('Finish')
  expect(screen.getByText(/Fictional session · this choice/)).toBeTruthy()
  click('Log')
  expect(screen.getByText(/Fictional session · this choice/)).toBeTruthy()
  click('Calm')
  expect(read().logs[0]).toMatchObject(real)
  expect(read().sessions[0].events.at(-1).text).toBe('Evening indicator: calm.')
  expect(screen.getByText('FICTIONAL EXAMPLE · Not a care record')).toBeTruthy()
})
it('keeps a skipped evening indicator unknown', async () => {
  await act(async () => render(<App/>))
  click('Start Moonrise now'); click('Skip launch'); click('Finish')
  click('Continue without an evening indicator')
  expect(read().logs).toEqual([])
  expect(read().sessions[0].events.some(event => event.text?.startsWith('Evening indicator:'))).toBe(false)
  expect(screen.getByRole('heading', {name:'Session handoff'})).toBeTruthy()
})
